				</div>
			<hr class='space'/>
			</div>

			<div id='footer' class='span-24 last' style='text-align: center; background-color: #fff;'>
				<div class='append-bottom'>
					<ul>
						<li><a class='hypertext' href='<?php echo $this->baseUrl(); ?>/about'>version <?php echo $this->config->misc->version; ?></a>
						<li><a class='hypertext' target='_blank' href='<?php echo $this->config->links->wiki; ?>'>wiki</a>
					</ul>
				</div>
			</div>
		</div>

		<div class='prepend-top append-bottom'>&nbsp;</div>
	</body>
</html>
