<div id='title' class='span-24' style='background-color: #ededed; line-height: 35px; height: 35px; position: relative;'>
	<div class='span-12'>
		<div style='padding-left: 10px; font-size: 1.6em;'>
			Miscellaneous Configurations
			<img class='progress' src='<?php echo $this->baseUrl(); ?>/usr/images/spinner.gif'>
		</div>
	</div>
	<div id='title-menu-holder' class='span-12 last' style='position: relative;'>
	<ul id="menu" style='float: right;'>
		<li class='trigger settings'>
			<img class='hypertext' style='margin-top: 8px; float: left; width: 16px; height: 16px;' src='<?php echo $this->baseUrl(); ?>/usr/images/type.png'><span style='float: left;' class='activeText darkHypertext'>&nbsp;</span>
			<ul class='sub-menu' style='z-index: 1000'>
				<li>
					<a href="#database" class='darkHypertext'>Database</a>
				</li>
				<li>
					<a href="#email" class='darkHypertext'>Email</a>
				</li>
				<li>
					<a href="#xmpp" class='darkHypertext'>Instant messaging</a>
				</li>
				<li>
					<a href="#paths" class='darkHypertext'>Paths</a>
				</li>
				<li>
					<a href="#ws" class='darkHypertext'>Web services</a>
				</li>
			</ul>
		</li>
	</ul>
	</div>
</div>
