<div id='notifications' class='span-22 prepend-top append-bottom prepend-1 append-1 config'>
	<div class='span-21'>
		<div class='span-21'>
			<strong>Email subject</strong>
			<div class='span-21'>
				<input type='text' name='subject' class='span-11' value='nessquik scan report'>
			</div>
		</div>

		<hr class='space'/>

		<div class='span-21'>
			<div class='span-11'>
				<strong>Report format</strong>
			</div>
			<div class='span-10 last'>
				<strong>Report example</strong>
			</div>
		</div>

		<div class='span-21 last'>
			<div class='span-11'>
				<div class='span-11'>
					<select name='reportFormat' class='span-11 report-format'>
						<?php if ($this->isNew || empty($this->notification)): ?>
						<optgroup label='Formats'>
							<option value='nessus'>nessus
							<option value='html'>html
							<option value='txt'>text
							<option value='nbe'>nbe
						</optgroup>
						<?php else: ?>
						<optgroup label='Formats'>
							<?php if ($this->notification['reportFormat'] == 'nessus'): ?>
							<option value='nessus' selected='selected'>nessus
							<?php else: ?>
							<option value='nessus'>nessus
							<?php endif; ?>

							<?php if ($this->notification['reportFormat'] == 'html'): ?>
							<option value='html' selected='selected'>html
							<?php else: ?>
							<option value='html'>html
							<?php endif; ?>

							<?php if ($this->notification['reportFormat'] == 'txt'): ?>
							<option value='txt' selected='selected'>text
							<?php else: ?>
							<option value='txt'>text
							<?php endif; ?>

							<?php if ($this->notification['reportFormat'] == 'nbe'): ?>
							<option value='nbe' selected='selected'>nbe
							<?php else: ?>
							<option value='nbe'>nbe
							<?php endif; ?>
						</optgroup>
						<?php endif; ?>
					</select>
				</div>

				<hr class='space'/>

				<div class='span-11'>
					<strong>Compress attachment?</strong>
				</div>
				<div class='span-11'>
					<?php if ($this->isNew || empty($this->notification)): ?>
					<input type='radio' name='compressAttachment' value='yes'>yes
					&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
					<input type='radio' name='compressAttachment' value='no' checked='checked'>no
					<?php else: ?>
						<?php if ($this->notification['compressAttachment'] == 'yes'): ?>
							<input type='radio' name='compressAttachment' value='yes' checked='checked'>yes
							&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
							<input type='radio' name='compressAttachment' value='no'>no
						<?php else: ?>
							<input type='radio' name='compressAttachment' value='yes'>yes
							&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
							<input type='radio' name='compressAttachment' value='no' checked='checked'>no
						<?php endif; ?>
					<?php endif; ?>
				</div>

				<hr class='space'/>

				<div class='span-11'>
					<strong>Send to me</strong>
				</div>
				<div class='span-11'>
					<?php if ($this->isNew || empty($this->notification)): ?>
					<input type='radio' name='sendToMe' value='yes' checked='checked'>yes
					&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
					<input type='radio' name='sendToMe' value='no'>no
					<?php else: ?>
						<?php if ($this->notification['sendToMe'] == 'yes'): ?>
						<input type='radio' name='sendToMe' value='yes' checked='checked'>yes
						&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
						<input type='radio' name='sendToMe' value='no'>no
						<?php else: ?>
						<input type='radio' name='sendToMe' value='yes'>yes
						&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
						<input type='radio' name='sendToMe' value='no' checked='checked'>no
						<?php endif; ?>
					<?php endif; ?>
				</div>
			</div>
			<div class='span-10 last prepend-top'>
				<div style='max-height: 150px; overflow: hidden; position: relative; z-index: 1;'>
					<div class='format-example nessus'>
						<img alt='Preview .nessus format' src='<?php echo $this->baseUrl(); ?>/usr/images/preview-nessus.png'>
					</div>
					<div class='format-example html'>
						<img alt='Preview HTML format' src='<?php echo $this->baseUrl(); ?>/usr/images/preview-html-v2.png'>
					</div>
					<div class='format-example txt'>
						<img alt='Preview text format' src='<?php echo $this->baseUrl(); ?>/usr/images/preview-text.png'>
					</div>
					<div class='format-example nbe'>
						<img alt='Preview nbe format' src='<?php echo $this->baseUrl(); ?>/usr/images/preview-nbe.png'>
					</div>
				</div>
			</div>
		</div>

		<hr class='space'/>

		<strong>Send to other people</strong>
		<div class='span-21 last'>
			<?php if ($this->isNew || empty($this->notification)): ?>
			<input type='radio' name='sendToOthers' value='yes'>yes
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			<input type='radio' name='sendToOthers' value='no' checked='checked'>no
			<?php else: ?>
				<?php if ($this->notification['sendToOthers'] == 'yes'): ?>
					<input type='radio' name='sendToOthers' value='yes' checked='checked'>yes
					&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
					<input type='radio' name='sendToOthers' value='no'>no
				<?php else: ?>
					<input type='radio' name='sendToOthers' value='yes'>yes
					&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
					<input type='radio' name='sendToOthers' value='no' checked='checked'>no
				<?php endif; ?>
			<?php endif; ?>
		</div>

		<hr class='space'/>

		<div class='span-21 send-to-others'>
			<div class='small quiet append-bottom'>
				The emailed reports will be sent from your email address
				and recipients will be able to reply to you.
			</div>
			<div class='span-17 prepend-1'>
				<div class='span-16'>
					<div class='span-4'>
						<strong>Additional recipients</strong>
					</div>
					<div class='span-12 last' style='text-align: right;'>
						<span class='hypertext add-recipient'>add recipient</span>
					</div>
				</div>

				<div id='recipientList'>
					<?php if ($this->isNew || empty($this->notification)): ?>
						<div class='recipient span-16'>
							<div class='span-13'>
								<input class='span-13' type='text' name='recipients[]' value=''>
							</div>
							<div class='span-3 last icons'>
								<div style='padding: 5px;'>
									<img class='trash' alt='Remove recipient' src='<?php echo $this->baseUrl(); ?>/usr/images/trash.gif'>
								</div>
							</div>
						</div>
					<?php else: ?>
						<?php if (empty($this->notification['recipients'])): ?>
							<div class='recipient span-16'>
								<div class='span-13'>
									<input class='span-13' type='text' name='recipients[]' value=''>
								</div>
								<div class='span-3 last icons'>
									<div style='padding: 5px;'>
										<img class='trash' src='<?php echo $this->baseUrl(); ?>/usr/images/trash.gif'>
									</div>
								</div>
							</div>
						<?php else: ?>
							<?php foreach ($this->notification['recipients'] as $recipient): ?>
							<div class='recipient span-16'>
								<div class='span-13'>
									<input class='span-13' type='text' name='recipients[]' value='<?php echo $recipient; ?>'>
								</div>
								<div class='span-3 last icons'>
									<div style='padding: 5px;'>
										<img class='trash' src='<?php echo $this->baseUrl(); ?>/usr/images/trash.gif'>
									</div>
								</div>
							</div>
							<?php endforeach; ?>
						<?php endif; ?>
					<?php endif; ?>
				</div>
			</div>
		</div>
		<div class='message error span-17 prepend-top'>
			<span class='content'></span>
			&nbsp;&nbsp;
			<span class='hypertext close'>close</span>
		</div>
	</div>
</div>
