<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/jquery/ui/jquery.ui.tabs.js' type='text/javascript'></script>
<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/jquery/plugins/jquery.dateentry/jquery.dateentry.min.js' type='text/javascript'></script>
<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/jquery/plugins/jquery.timeentry/jquery.timeentry.min.js' type='text/javascript'></script>
<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/jquery/plugins/jquery.mousewheel/jquery.mousewheel.min.js' type='text/javascript'></script>
<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/jquery/plugins/jquery.shiftcheckbox.js' type='text/javascript'></script>
<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/jquery/plugins/jquery.watermarkinput.js' type='text/javascript'></script>
<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/jquery/plugins/jquery.pager.js' type='text/javascript'></script>
<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/date.js' type='text/javascript'></script>

<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/audit/modify/edit.js' type='text/javascript'></script>
<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/audit/modify/scheduling.js' type='text/javascript'></script>
<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/audit/modify/reports.js' type='text/javascript'></script>
<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/audit/modify/email.js' type='text/javascript'></script>
<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/audit/modify/notifications.js' type='text/javascript'></script>
<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/audit/modify/nessusv2-inline.js' type='text/javascript'></script>
<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/audit/modify/includeTarget.js' type='text/javascript'></script>
<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/audit/modify/excludeTarget.js' type='text/javascript'></script>
