<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/datejs/i18n/en-US.js' type='text/javascript'></script>
<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/datejs/core.js' type='text/javascript'></script>
<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/datejs/parser.js' type='text/javascript'></script>
<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/default/index.js' type='text/javascript'></script>
<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/jquery/plugins/jquery.timers.js' type='text/javascript'></script>
<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/jquery/plugins/jquery.fullcalendar/fullcalendar.js' type='text/javascript'></script>
