<?php if($this->action == 'edit'): ?>
	<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/admin/authentication/edit.js' type='text/javascript'></script>
<?php elseif ($this->action == 'index'): ?>
	<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/jquery/plugins/jquery.shiftcheckbox.js' type='text/javascript'></script>
	<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/admin/authentication/index.js' type='text/javascript'></script>
<?php endif; ?>
