<?php require _MODPATH.'/default/views/scripts/header/index.phtml'; ?>
<?php require _MODPATH.'/charts/views/scripts/header/index.phtml'; ?>

<div class='span-22'>
	<form id='form-edit'>
		<input type='hidden' name='base-url' value='<?php echo $this->baseUrl(); ?>'>
	</form>

	<div id='countryExposure' class='span-22 append-bottom'>
		<div class='span-22'>
			<strong>About this chart</strong>
		</div>
		<div class='small quiet append-bottom span-22'>
			This map shows the countries which the URLs in savory originate from.
			The darker the country, the more URLs we have recorded for that country
		</div>
		<div class='message error span-22'>
			<div class='content'></div>
		</div>
		<div id='countryExposureChart' class='span-22' style='height: 220px; text-align: center;'></div>
	</div>

	<div class='span-22 prepend-top append-bottom'>
		<div id='tableData' class='span-22'>Please wait while the table data is retrieved</div>
		<div id='pager' class='span-22 prepend-top' style='text-align: center;'>
			<form>
				<img class="first" src="<?php echo $this->baseUrl(); ?>/usr/images/first.png">
				<img class="prev" src="<?php echo $this->baseUrl(); ?>/usr/images/prev.png">
				<input type="text" class="pagedisplay">
				<img class="next" src="<?php echo $this->baseUrl(); ?>/usr/images/next.png">
				<img class="last" src="<?php echo $this->baseUrl(); ?>/usr/images/last.png">
				<select class="pagesize">
					<option value="10" selected="selected">10</option>
					<option value="20">20</option>
					<option value="30">30</option>
					<option value="40">40</option>
				</select>
			</form>
		</div>
	</div>
</div>

<?php require _MODPATH.'/default/views/scripts/footer/index.phtml'; ?>
