<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/jquery/plugins/jquery.gchart/jquery.gchart.js' type='text/javascript'></script>
<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/jquery/plugins/jquery.tablesorter.min.js' type='text/javascript'></script>
<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/jquery/plugins/jquery.tablesorter.pager.js' type='text/javascript'></script>
<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/charts/country-exposure/index/index.js' type='text/javascript'></script>
