<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/jquery/plugins/jquery.shiftcheckbox.js' type='text/javascript'></script>
<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/jquery/plugins/jquery.ba-throttle-debounce.min.js' type='text/javascript'></script>
<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/jquery/plugins/jquery.pager.js' type='text/javascript'></script>
<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/jquery/ui/jquery.ui.tabs.js' type='text/javascript'></script>
<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/admin/policy/index.js' type='text/javascript'></script>
