<div id='faqDialog'>
	<div class='span-10' style='border-bottom: 1px solid #eee; background-color: #eee; height: 35px; min-height: 35px;'>
		<div style='padding: 10px;'>
			<div style='color: #303233; font-weight: bold;'>
				Help
			</div>
		</div>
	</div>

	<div class='prepend-1 append-1 prepend-top append-bottom span-8'>
		<p>
		Account maps assist in mapping usernames that may exist or be
		used in other authentication methods to IDs that are stored
		in nessquik.
		</p>
		<p>
		Maps are most useful if you have users with several different
		account names and want those users to be able to access their
		saved audits, policies, etc, even if they log in with a different
		authentication method.
		</p>
	</div>

	<div class='span-10' style='height: 35px; background-color: #eee; text-align: center; padding-top: 10px;'>
		<input id='faqDialogClose' type='button' value='Ok, thanks!'>
	</div>
</div>
