<div class='span-22 prepend-top append-bottom prepend-1 append-1'>
	<div class='permission-block network-target'>
		<strong>Audits</strong>

		<div class='span-22'>
			<div class='span-5'>
				Available audits
			</div>
			<div class='span-5' style='text-align: right;'>&nbsp;</div>
			<div class='span-2'>&nbsp;</div>
			<div class='span-5'>
				Selected audits
			</div>
			<div class='span-5 last' style='text-align: right;'>
				<span class='hypertext clear-all'>clear all &laquo;</span>
			</div>
		</div>

		<div class='permissions span-22'>
			<div class='span-10'>
				<ol class='selectable available'>
					<?php if (!empty($this->audits)): ?>
					<?php foreach($this->audits as $audit): ?>
						<?php if ($this->inSelected($audit['permission_resource'], $this->selectedAudits)): ?>
						<li class='<?php echo $audit['permission_id']; ?>'>
							<input type='hidden' name='available-audit[]' value='<?php echo $audit['permission_id']; ?>'>
							<img src='<?php echo $this->baseUrl(); ?>/usr/images/forward-selected.png'>&nbsp;&nbsp;
							<span><?php echo $audit['permission_resource']; ?></span>
						<?php else: ?>
						<li class='<?php echo $audit['permission_id']; ?>'>
							<input type='hidden' name='available-audit[]' value='<?php echo $audit['permission_id']; ?>'>
							<img src='<?php echo $this->baseUrl(); ?>/usr/images/forward.png'>&nbsp;&nbsp;
							<span><?php echo $audit['permission_resource']; ?></span>
						<?php endif; ?>
					<?php endforeach; ?>
					<?php endif; ?>
				</ol>
			</div>
			<div class='span-2'>&nbsp;</div>
			<div class='span-10 last'>
				<ol class='selectable selected'>
					<?php if (!empty($this->selectedAudits)): ?>
					<?php foreach($this->selectedAudits as $audit): ?>
						<li class='<?php echo $audit['id']; ?>'>
							<input type='hidden' name='selected-audit[]' value='<?php echo $audit['id']; ?>'>
							<img src='<?php echo $this->baseUrl(); ?>/usr/images/back.png'>&nbsp;&nbsp;
							<span><?php echo $audit['resource']; ?></span>
					<?php endforeach; ?>
					<?php endif; ?>
				</ol>
			</div>
		</div>
	</div>
</div>
