<div class='span-22 prepend-top append-bottom prepend-1 append-1'>
	<div class='permission-block'>
		<strong>API Methods</strong>

		<div class='span-22'>
			<div class='span-5'>
				Available API calls
			</div>
			<div class='span-5' style='text-align: right;'>
				<span class='hypertext add-all'>add all &raquo;</span>
			</div>
			<div class='span-2'>&nbsp;</div>
			<div class='span-5'>
				Selected API calls
			</div>
			<div class='span-5 last' style='text-align: right;'>
				<span class='hypertext clear-all'>clear all &laquo;</span>
			</div>
		</div>

		<div class='permissions span-22'>
			<div class='span-10'>
				<ol class='selectable available'>
					<?php if (!empty($this->allMethods)): ?>
					<?php foreach($this->allMethods as $method): ?>
						<?php if ($this->inSelected($method['permission_resource'], $this->selectedMethods)): ?>
						<li class='<?php echo $method['permission_id']; ?>'>
							<input type='hidden' name='available-api[]' value='<?php echo $method['permission_id']; ?>'>
							<img src='<?php echo $this->baseUrl(); ?>/usr/images/forward-selected.png'>&nbsp;&nbsp;
							<span><?php echo $method['permission_resource']; ?></span>
						<?php else: ?>
						<li class='<?php echo $method['permission_id']; ?>'>
							<input type='hidden' name='available-api[]' value='<?php echo $method['permission_id']; ?>'>
							<img src='<?php echo $this->baseUrl(); ?>/usr/images/forward.png'>&nbsp;&nbsp;
							<span><?php echo $method['permission_resource']; ?></span>
						<?php endif; ?>
					<?php endforeach; ?>
					<?php endif; ?>
				</ol>
			</div>
			<div class='span-2'>&nbsp;</div>
			<div class='span-10 last'>
				<ol class='selectable selected'>
					<?php if (!empty($this->selectedMethods)): ?>
					<?php foreach($this->selectedMethods as $method): ?>
						<li class='<?php echo $method['id']; ?>'>
							<input type='hidden' name='selected-api[]' value='<?php echo $method['id']; ?>'>
							<img src='<?php echo $this->baseUrl(); ?>/usr/images/back.png'>&nbsp;&nbsp;
							<span><?php echo $method['resource']; ?></span>
					<?php endforeach; ?>
					<?php endif; ?>
				</ol>
			</div>
		</div>
	</div>
</div>
