<div id='title' class='span-24' style='background-color: #ededed; line-height: 35px; height: 35px; position: relative;'>
	<div class='span-5'>
		<div style='padding-left: 10px; font-size: 1.6em;'>
			<a href='<?php echo $this->baseUrl(); ?>/admin/roles' class='hypertext'>Roles</a> &raquo;
<?php if ($this->isNew === true): ?>
			<span>Create role</span>
<?php else: ?>
			<span>Edit role</span>
<?php endif; ?>
			<img class='progress' src='<?php echo $this->baseUrl(); ?>/usr/images/spinner.gif'>
		</div>
	</div>
	<div id='menu' class='span-19 last' style='text-align: right;'>
		<div class='pluginLinks'>
			<ul>
				<li><a href='<?php echo $this->baseUrl(); ?>/audit/modify/edit?id=_new' class='darkHypertext'>Modify permissions</a>
			</ul>
		</div>
	</div>
</div>
