<?php require _MODPATH.'/default/views/scripts/header/empty.phtml' ?>

<div style='font-family: Verdana; font-size: 76%; padding: 0px 150px 0px 150px;'>
	<h1 style='font-size: 4.4em; letter-spacing: -1px; line-height: 0.97em; font-family: Helvetica; font-weight: bold;'>
		Oops...
	</h1>
	<div style='color:#888888; font-family:Georgia,Times,Serif; font-size:1.5em; font-size-adjust:none; font-stretch:normal; font-style:italic; font-variant:normal; font-weight:normal; line-height:1.67em;'>
		<p>
		Hi. I'm CST's nessquik server. It looks like you either found a bug in nessquik,
		or navigated to a page that doesn't exist! I (the nessquik server) take bugs 
		seriously and have automatically notified the members of CST who are most capable 
		of fixing the problem.
		</p>
	</div>

	<br>

	<div style='background:#EFEFEF none repeat scroll 0 0; border:1px solid #CCCCCC; display:block; font-size:1.2em; margin:0 0 1.4em; padding:1em; margin-left: 3em; margin-right: 3em; text-align:center;'>
		I'm terribly sorry for the inconvenience. If this was a just a hiccup, you 
		may be able to return to <a href='<?php echo $this->baseUrl(); ?>/'>nessquik</a> and continue working.
	</div>

	<div>
		If that doesn't do the trick, try contacting...

		<ul>
			<li>...the <a href='http://helpdesk.fnal.gov'>Helpdesk</a>
			<li>...the Computer Security Team
		</ul>

		<p>
		Or, if you're really lost, contact Tim. He can be reached...

		<ul>
			<li>...via instant messenger at <span style='font-weight: bold;'>tarupp@jabber.fnal.gov</span>
			<li>...via email at <span style='font-weight: bold;'>tarupp@fnal.gov</span>
			<li>...via Twitter; tweet <a href='http://twitter.com/caphrim007' target='_blank' style='text-decoration: none; font-weight: bold;'>caphrim007</a>
		</ul>
	</div>
</div>

<?php require _MODPATH.'/default/views/scripts/footer/empty.phtml' ?>
