<?php require _MODPATH.'/default/views/scripts/header/index.phtml'; ?>

<hr class='space'/>

<div class='span-22 prepend-1 append-1'>
	<div class='error'>
		You do not have the permission to access this resource
	</div>
</div>

<div class='span-22 prepend-1 append-1 prepend-top append-bottom' style='text-align: center;'>
	Return from <a class='hypertext' href='<?php echo $_SERVER['HTTP_REFERER']; ?>'>whence</a> you came
</div>

<?php require _MODPATH.'/default/views/scripts/footer/index.phtml'; ?>
