<div id='title' class='span-24' style='background-color: #ededed; line-height: 35px; height: 35px; position: relative;'>
	<div class='span-12'>
		<div style='padding-left: 10px; font-size: 1.6em;'>
			<a href='<?php echo $this->baseUrl(); ?>/admin/account' class='hypertext'>Accounts</a> &raquo;
			<a href='<?php echo $this->baseUrl(); ?>/account/modify/edit?id=<?php echo $this->accountId; ?>' class='hypertext'><?php echo $this->account->username; ?></a> &raquo;
			Roles
			<img class='progress' src='<?php echo $this->baseUrl(); ?>/usr/images/spinner.gif'>
		</div>
	</div>
	<div id='title-menu-holder' class='span-12 last'></div>
</div>
