<div id='policy' class='wrapper clearfix'>
	<div>
		<form class='search'>
			<input type='hidden' name='page' value='1'>
			<input type='hidden' name='old-page' value='1'>
		</form>
	</div>
	<div class='span-13 colborder'>
		<strong>Select a policy to use</strong>
		<div class='block policy-list prepend-top'>
			<div class='search-results'>
				<div style='padding: 10px;' class='span-13'>
					<div class='content'></div>
				</div>
			</div>
		</div>
	</div>
	<div class='span-6 last' style='text-align: justify;'>
		<p>
		Choose the policy that you want to use for this audit.
		</p>
		<p>
		The policy controls how the audit behaves when run against
		a set of targets. All the settings for the audit are
		contained in these policies.
		</p>
	</div>
</div>
