<?php require _MODPATH.'/setup/views/scripts/header/index.phtml'; ?>

<div class='span-22 last'>
	<div class='span-22'>
		<div class='span-22' style='font-size: 1.5em;'>
			<a href='<?php echo $this->baseUrl(); ?>/setup' class='hypertext'>Setup</a> &raquo;
			Document storage
		</div>
	</div>
</div>
<hr class='space'/>
<div class='span-22'>
	<form id='form-edit'>
		<input type='hidden' name='base-url' value='<?php echo $this->baseUrl(); ?>'>
	</form>

	<form id='form-submit'>
		<strong>About</strong>
		<div class='prepend-top'>
			<p>
			Next let's set up the document storage backend that nessquik will use to store various
			pieces of unstructured data.
			</p>
			<p>
			The backend you use may or may not include authentication related data. If you know it
			doesn't (and you're sure you want to proceed that way) feel free to disregard the username
			and password portions of the following form.
			</p>
			<p>
			If, on the other hand, this concerns you, feel free to refer to my recommendation for how to 
			<a class='hypertext' target='_blank' href='<?php echo $this->config->links->wiki; ?>:<?php echo $this->config->misc->version; ?>:manuals:admin:authenticated_proxy'>secure non-authenticated services</a>
			behind an Apache proxy.
			</p>
		</div>

		<hr class='quiet'/>

		<div class='span-22 append-bottom'>
			<div class='span-3'>
				<strong>Storage scheme</strong>
				<div>
					<select name='scheme' class='span-3'>
						<?php if ($this->config->database->couch->params->scheme == 'https'): ?>
						<option value='http'>HTTP
						<option value='https' selected='selected'>HTTPS
						<?php else: ?>
						<option value='http' selected='selected'>HTTP
						<option value='https'>HTTPS
						<?php endif; ?>
					</select>
				</div>
			</div>

			<div class='span-7'>
				<strong>Storage host</strong>
				<div>
					<input type='text' name='host' value='<?php echo $this->config->database->couch->params->host; ?>' class='span-7'>
				</div>
			</div>

			<div class='span-2'>&nbsp;</div>

			<div class='span-6 last'>
				<strong>Storage port</strong>
				<div>
					<input type='text' name='port' value='<?php echo $this->config->database->couch->params->port; ?>'>
				</div>
			</div>
		</div>

		<div class='span-22 append-bottom'>
			<strong>Storage name</strong>
			<div>
				<input type='text' name='dbname' value='<?php echo $this->config->database->couch->params->dbname; ?>' class='span-10'>
			</div>
		</div>

		<div class='span-22 append-bottom'>
			<div class='span-10'>
				<strong>Username</strong>
				<div>
					<input type='text' name='username' value='<?php echo $this->config->database->couch->params->username; ?>' class='span-10'>
				</div>
			</div>

			<div class='span-2'>&nbsp;</div>

			<div class='span-10 last'>
				<strong>Password</strong>
				<div>
					<input type='text' name='password' value='<?php echo $this->config->database->couch->params->password; ?>' class='span-10'>
				</div>
			</div>
		</div>

		<hr class='space'/>

		<div class='message error append-bottom'>
			<span class='content'></span>
			&nbsp;&nbsp;
			<span class='hypertext close'>close</span>
		</div>

		<div class='span-22 last clearfix form-ops' style='text-align: center;'>
			<input id='btn-save' type='button' value='Test connection'>
			<img class='progress' src='<?php echo $this->baseUrl(); ?>/usr/images/spinner.gif'>
		</div>

		<div class='span-22 append-bottom prepend-top'>
			<div class='span-22'>
				&laquo; <a class='hypertext' href='<?php echo $this->baseUrl(); ?>/setup/database'>Database</a>
			</div>
		</div>
	</form>
</div>

<?php require _MODPATH.'/setup/views/scripts/footer/index.phtml'; ?>
