<?php require _MODPATH.'/default/views/scripts/header/index.phtml'; ?>

<div class='span-22 last'>
	<div class='span-22' style='font-size: 1.5em;'>
		Account Defaults
	</div>
</div>
<hr class='space'/>
<div class='span-21'>
	<form id='form-edit'>
		<input type='hidden' name='base-url' value='<?php echo $this->baseUrl(); ?>'>
	</form>
	<form id='form-submit'>
		<strong>Default assigned roles</strong>
		<div class='small quiet'>
			Choose which roles, if any, you would like to have
			assigned to new accounts when they are first created
		</div>
		<div class='permission-block'>
			<div class='span-4'>
				Available roles
			</div>
			<div class='span-6' style='text-align: right;'>
				<span class='hypertext add-all'>add all &raquo;</span>
			</div>
			<div class='span-1'>&nbsp;</div>
			<div class='span-4'>
				Selected roles
			</div>
			<div class='span-6 last' style='text-align: right;'>
				<span class='hypertext clear-all'>clear all &laquo;</span>
			</div>
			<div class='roles'>
				<div class='span-10'>
					<ol class='selectable available'>
						<?php if (!empty($this->allRoles)): ?>
						<?php foreach($this->allRoles as $role): ?>
							<?php if (array_key_exists($role['id'], $this->selectedRoles)): ?>
							<li class='<?php echo $role['id']; ?>'>
								<input type='hidden' name='available-role[]' value='<?php echo $role['id']; ?>'>
								<img src='<?php echo $this->baseUrl(); ?>/usr/images/forward-selected.png'>&nbsp;&nbsp;
								<span><?php echo $role['name']; ?></span>
							<?php else: ?>
							<li class='<?php echo $role['id']; ?>'>
								<input type='hidden' name='available-role[]' value='<?php echo $role['id']; ?>'>
								<img src='<?php echo $this->baseUrl(); ?>/usr/images/forward.png'>&nbsp;&nbsp;
								<span><?php echo $role['name']; ?></span>
							<?php endif; ?>
						<?php endforeach; ?>
						<?php endif; ?>
					</ol>
				</div>
				<div class='span-1'>&nbsp;</div>
				<div class='span-10 last'>
					<ol class='selectable selected'>
						<?php if (!empty($this->selectedRoles)): ?>
						<?php foreach($this->selectedRoles as $key => $role): ?>
							<li class='<?php echo $key; ?>'>
								<input type='hidden' name='selected-role[]' value='<?php echo $key; ?>'>
								<img src='<?php echo $this->baseUrl(); ?>/usr/images/back.png'>&nbsp;&nbsp;
								<span><?php echo $role; ?></span>
						<?php endforeach; ?>
						<?php endif; ?>
					</ol>
				</div>
			</div>
		</div>

		<div class='message span-21'>
			<div class='error content prepend-top append-bottom'></div>
		</div>

		<hr class='space'/>

		<div class='span-20 last clearfix form-ops' style='text-align: center;'>
			<input id='btn-save' type='button' value='Save'>
			<a class='hypertext' style='padding-left: 20px;' href='<?php echo $this->baseUrl(); ?>/admin'>cancel</a>
		</div>
	</form>
</div>

<?php require _MODPATH.'/default/views/scripts/footer/index.phtml'; ?>
