<!-- scaffolding for recipients box on notifications page -->
<div id='scaffolding'>
	<div class='recipient span-16'>
		<div class='span-13'>
			<input class='span-13' type='text' name='recipients[]' value=''>
		</div>
		<div class='span-3 last icons'>
			<div style='padding: 5px;'>
				<img class='trash' src='<?php echo $this->baseUrl(); ?>/usr/images/trash.gif'>
			</div>
		</div>
	</div>
</div>
