<div>
	<ul style='padding-left: 0px;'>
		<li><span class='hypertext motdLink'>Notice to users</span>
	</ul>
	<div id='motdDiag' style='text-align: justify'>
		<div class='span-18' style='border-bottom: 1px solid #eee; background-color: #eee; height: 45px; min-height: 45px;'>
			<div style='padding: 10px;'>
				<div style='color: #303233; font-weight: bold;'>
					Notice to users
				</div>
			</div>
		</div>

		<div class='span-18 last'>
			<div style='padding: 10px;'>
				<p>
				This is a Federal computer (and/or it is directly connected to a
				Fermilab local network system) that is the property of the United
				States Government. It is for authorized use only. Users (authorized
				or unauthorized) have no explicit or  implicit  expectation of privacy.
				</p>
				<p>
				Any or all uses of this system and all files on this system may
				be intercepted, monitored, recorded, copied, audited, inspected,
				and disclosed to authorized site, Department of Energy and law
				enforcement personnel, as  well as authorized officials of other
				agencies, both  domestic and foreign. By using this system, the
				user consents to such interception, monitoring, recording, copying,
				auditing, inspection, and disclosure at the discretion of
				authorized site or Department of Energy personnel.
				</p>
				<p>
				Unauthorized or improper use of this system may result in administrative
				disciplinary action and civil and criminal penalties.
				By continuing to use this system you indicate your awareness of
				and consent to these terms and conditions of use. LOG OFF IMMEDIATELY
				if you do not agree to the conditions stated in this warning.
				</p>
				<p>
				Fermilab policy and rules for computing, including appropriate
				use, may be found at http://www.fnal.gov/cd/main/cpolicy.html
				</p>
			</div>
		</div>

		<div class='span-18 last' style='height: 50px; background-color: #eee; text-align: center;'>
			<div style='padding-top: 10px;'>
				<input type='button' id='btn-ok' value='Ok'>
			</div>
		</div>
	</div>
</div>
