<div id="account-info" class='clearfix'>
	<div class='span-13 colborder'>
		<strong>Displayed name</strong>
		<div>
			<input type='text' name='displayed-name' style='width: 100%;'>
		</div>

		<hr class='space'/>

		<strong>Primary email</strong>
		<div>
			<input type='text' name='primary-contact-email' value='' style='width: 100%;'>
		</div>

		<hr class='space'/>

		<strong>Secondary email</strong>
		<div>
			<input type='text' name='secondary-contact-email' value='' style='width: 100%;'>
		</div>

		<hr class='space'/>

		<div>
			<span class='hypertext'>Other forms of communication</span>
		</div>
	</div>
	<div class='span-6 last' style='text-align: justify;'>
		<p>
		General account information can be changed here
		</p>
		<p>
		</p>
	</div>
</div>
