<div id="change-password" class='clearfix'>
	<form id='change-password-frm'>
		<div class='span-13 colborder'>
			<strong>Old Password</strong>
			<div>
				<input type='text' name='old-password' value='New policy' style='width: 100%;'>
			</div>
	
			<hr class='space'/>

			<strong>New Password</strong>
			<div>
				<input type='text' name='new-password' style='width: 100%;'>
			</div>

			<hr class='space'/>

			<strong>Confirm New Password</strong>
			<div>
				<input type='text' name='confirm-new-password' style='width: 100%;'>
			</div>
		</div>
		<div class='span-6 last' style='text-align: justify;'>
			<p>
			Change your nessquik password
			</p>
			<p>
			Your password can only be changed if you are using
			database authentication.
			</p>
			<p>
			If you rely on LDAP, Active Directory or Certificates,
			you must use the facilities available in those services
			to change your password.
			</p>
		</div>
	</form>
</div>
