<div id="interface" class='clearfix'>
	<div class='span-13 colborder'>
		<strong>Default policy editor</strong>
		<div>
			<input type='radio' name='default-policy-editor' value='simple'>Simple<br>
			<input type='radio' name='default-policy-editor' value='advanced'>Advanced
		</div>
	</div>
	<div class='span-6 last' style='text-align: justify;'>
		<p>
		Interface settings let you change how nessquik looks and behaves.
		</p>
		<p>
		Most of these settings can be adjusted during normal use.
		</p>
		<p>
		For instance, you may typically use the simple plugin editor,
		but for one particular case you need to use the advanced editor.
		</p>
		<p>
		You can switch to the advanced editor on the policy page, do
		what you need to do, and still have the simple editor be your
		default editor.
		</p>
	</div>
</div>
