<div id="keys" class='clearfix'>
	<div class='span-13 colborder'>
		<strong>SSH Public Keys</strong>
		<div>
			Put public keys here
		</div>

		<strong>SSH Private Keys</strong>
		<div>
			Put public keys here
		</div>

		<strong>SSH known_host files</strong>
		<div>
			Put public keys here
		</div>

		<strong>SSL certificates</strong>
		<div>
			Put public keys here
		</div>

		<strong>SSL CAs</strong>
		<div>
			Put public keys here
		</div>

		<strong>SSL Keys</strong>
		<div>
			Put public keys here
		</div>
	</div>
	<div class='span-6 last' style='text-align: justify;'>
		<p>
		Interface settings let you change how nessquik looks and behaves.
		</p>
		<p>
		Most of these settings can be adjusted during normal use.
		</p>
		<p>
		For instance, you may typically use the simple plugin editor,
		but for one particular case you need to use the advanced editor.
		</p>
		<p>
		You can switch to the advanced editor on the policy page, do
		what you need to do, and still have the simple editor be your
		default editor.
		</p>
	</div>
</div>
