<div id="notifications" class='clearfix'>
	<div class='span-13 colborder'>
		<strong>How should we notify you?</strong>
		<div id='notifications'>
			<select id='how-to-notify' name='how-to-notify'>
				<option value=''>Choose
				<option value='contact-email'>Primary email address
				<option value='secondary-email'>Secondary email address
				<option value='jabber'>Jabber
				<option value='twitter'>Tweet
				<option value='phone-call'>Phone call
			</select>
			<div id="contact-email" class='notice'>
				Emails you receive will be sent from <span class='hypertext'>nightwatch@fnal.gov</span>
			</div>
		</div>

		<hr class='space'/>
	
		<strong>Mobile notifications</strong>
		<div>
			<input type='text' name='mobile-contact[]' style='width: 100%;'>
		</div>
		<div>
			<span class='hypertext'>add another</span>
		</div>
	</div>
	<div class='span-6 last' style='text-align: justify;'>
		<p>
		Policies specify how an audit should operate.
		</p>
		<p>
		The general settings on this page will not affect how
		the audit runs, they are mainly just informational fields
		that will allow you to remember what policies you have
		created
		</p>
	</div>
</div>
