<div class='span-22 last metrxBreadcrumb reportBreadcrumb'>
	<div class='span-12' style='font-size: 1.5em;'>
		<a href='<?php echo $this->baseUrl(); ?>/metrx#reports' class='hypertext'>Reports</a> &raquo;
		<a class='currentCrumb' href='<?php echo sprintf("%s/reports/%s", $this->baseUrl(), $this->controller); ?>' style='text-decoration: none;'><?php echo $this->report->label; ?></a>
		<img class='progress' src='<?php echo $this->baseUrl(); ?>/usr/images/spinner.gif'>
	</div>
	<?php if (isset($this->report->exports)): ?>
	<div class='span-10 last small' style='text-align: right;'>
		Download as

		<?php $exports = explode(',', $this->report->exports); ?>
		<?php foreach($exports as $key => $export): ?>
			<a href='<?php echo $this->baseUrl(); ?>/reports/<?php echo $this->controller; ?>/download?format=<?php echo $export; ?>' class='span-2 hypertext'><?php echo $export ?></a>
			<?php if ((count($exports) - 1) != $key): ?>
			&nbsp;<span style='color: #ccc;'>|</span>&nbsp;
			<?php endif; ?>
		<?php endforeach; ?>
	</div>
	<?php else: ?>
	<div class='span-10 last'>&nbsp;</div>
	<?php endif; ?>
</div>
<hr class='space'/>
