<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/jquery/ui/jquery.ui.tabs.js' type='text/javascript'></script>
<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/jquery/plugins/jquery.shiftcheckbox.js' type='text/javascript'></script>
<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/jquery/plugins/jquery.watermarkinput.js' type='text/javascript'></script>
<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/date.js' type='text/javascript'></script>
<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/site-audit/options/index.js' type='text/javascript'></script>
<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/site-audit/options/index/email.js' type='text/javascript'></script>
<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/site-audit/options/index/notifications.js' type='text/javascript'></script>
