<div id='title' class='span-24' style='background-color: #ededed; line-height: 35px; height: 35px; position: relative;'>
	<div class='span-12'>
<?php if ($this->isNew === true): ?>
		<div style='padding-left: 10px; font-size: 1.6em;'>
			<a href='<?php echo $this->baseUrl(); ?>/admin/account' class='hypertext'>Accounts</a> &raquo;
			<span>Create</span>
			<img class='progress' src='<?php echo $this->baseUrl(); ?>/usr/images/spinner.gif'>
		</div>
<?php else: ?>
		<div style='padding-left: 10px; font-size: 1.6em;'>
			<a href='<?php echo $this->baseUrl(); ?>/admin/account' class='hypertext'>Accounts</a> &raquo;
			<span>Edit</span>
			<img class='progress' src='<?php echo $this->baseUrl(); ?>/usr/images/spinner.gif'>
		</div>
<?php endif; ?>
	</div>
	<div id='title-menu-holder' class='span-12 last' style='position: relative;'>
	</div>
</div>
