<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/jquery/plugins/jquery.autocomplete/jquery.autocomplete.min.js' type='text/javascript'></script>
<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/jquery/plugins/jquery.watermarkinput.js' type='text/javascript'></script>
<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/jquery/plugins/jquery.tablesorter.min.js' type='text/javascript'></script>
<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/jquery/plugins/jquery.tablesorter.pager.js' type='text/javascript'></script>

<?php if ($this->action == 'index'): ?>
<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/reports/whitelist-reconcile/index.js' type='text/javascript'></script>
<?php elseif ($this->action == 'setup'): ?>
<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/reports/whitelist-reconcile/setup.js' type='text/javascript'></script>
<?php elseif ($this->action == 'create') : ?>
<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/reports/whitelist-reconcile/create.js' type='text/javascript'></script>
<?php elseif ($this->action == 'history') : ?>
<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/reports/whitelist-reconcile/history.js' type='text/javascript'></script>
<?php endif; ?>
