<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
"http://www.w3.org/TR/html4/strict.dtd">
<html>
	<head>
		<title>nessquik</title>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
		<meta http-equiv="Pragma" content="no-cache">
		<meta http-equiv="Expires" content="-1">
		<meta name="copyright" content="&copy;">
		<meta name="Author" content="Tim Rupp">
		<link rel='icon' type='image/png' href='<?php echo $this->baseUrl(); ?>/usr/images/favicon.png'>
	</head>
	<body>
