<div id='title' class='span-24' style='background-color: #ededed; line-height: 35px; height: 35px;'>
	<div class='span-5'>
		<div style='padding-left: 10px; font-size: 1.6em;'>
			Audit Servers
			<img class='progress' src='<?php echo $this->baseUrl(); ?>/usr/images/spinner.gif'>
		</div>
	</div>

	<div class='span-19 last menu' style='text-align: right;'>
		<div class='pluginLinks'>
			<ul>
				<li><a href='<?php echo $this->baseUrl(); ?>/scanners/modify/edit?id=_new' class='darkHypertext'>Create</a>
			</ul>
		</div>
	</div>
</div>
