<div id='audit-finished' class='block clearfix menu-content'>
	<form name='search'>
		<input type='hidden' name='page' value='1'>
		<input type='hidden' name='old-page' value='1'>
		<input type='hidden' name='status' value='F'>
		<input type='hidden' name='statusText' value='finished'>
	</form>
	<div class='select-actions span-15 last'>
		Select: <span class='hypertext select-all'>All</span>, <span class='hypertext select-none'>None</span>
	</div>

	<div class='search-results span-15 last'>
		<div style='padding: 10px;' class='span-14'>
			<div class='content'></div>
		</div>
	</div>
</div>
