<!-- scaffolding for recipients box on notifications page -->
<div id='scaffolding'>
	<div class='span-22 xmpp recipient'>
		<div class='span-21'>
			<input type='text' name='xmppContact[]' value='' class='span-21'>
		</div>
		<div class='span-1 last icons' style='text-align: center;'>
			<img class='trash' style='padding-top: 10px;' src='<?php echo $this->baseUrl(); ?>/usr/images/trash.gif' title='remove'>
		</div>
	</div>

	<div class='span-22 email recipient'>
		<div class='span-21'>
			<input type='text' name='emailContact[]' value='' class='span-21'>
		</div>
		<div class='span-1 last icons' style='text-align: center;'>
			<img class='trash' style='padding-top: 10px;' src='<?php echo $this->baseUrl(); ?>/usr/images/trash.gif' title='remove'>
		</div>
	</div>
</div>
