<?php require _MODPATH.'/default/views/scripts/header/index.phtml'; ?>
<?php require _MODPATH.'/reports/views/scripts/header/index.phtml'; ?>

<div class='span-22'>
	<form id='form-edit'>
		<input type='hidden' name='base-url' value='<?php echo $this->baseUrl(); ?>'>
	</form>

	<div class='quiet span-22 append-bottom'>
		<p class='prepend-top'>
		The list below is the current list of blackholed domains in your
		Infoblox appliance.
		</p>
		<p>
		From here you can select which domains you may want to remove from
		the blackhole.
		</p>
		<p>
		Notice that the list includes the blackhole status as known by Infoblox.
		</p>
		<p>
		If the Infoblox appliance is not reporting that the domain is blackholed,
		then it is <span style='font-weight: bold; color: #000;'>not</span> blackholed; regardless
		of what savory says.
		</p>
	</div>

	<div class='message error span-22'>
		<span class='content'></span>
		&nbsp;&nbsp;
		<span class='hypertext close'>close</span>
	</div>

	<form id='form-submit'>
		<div id='blackholeBlock' class='span-22 last clearfix form-ops append-bottom' style='text-align: center;'>
			Please wait a moment while I fetch the URL list
		</div>
	</form>

	<div id='form-ops' class='span-22 clearfix append-bottom' style='text-align: center;'>
		<input id='btn-save' type='button' value='Reconcile selected URLs'>
		<a class='hypertext' style='padding-left: 20px;' href='<?php echo sprintf("%s/reports/%s", $this->baseUrl(), $this->controller); ?>'>cancel</a>
	</div>
</div>

<?php require _MODPATH.'/default/views/scripts/footer/index.phtml'; ?>
