<div id='faqDialog'>
	<div class='span-10' style='border-bottom: 1px solid #eee; background-color: #eee; height: 35px; min-height: 35px;'>
		<div style='padding: 10px;'>
			<div style='color: #303233; font-weight: bold;'>
				Help
			</div>
		</div>
	</div>

	<div class='prepend-1 append-1 prepend-top append-bottom span-8'>
		<p>
		You can change your password using the associated form
		</p>
		<p>
		When changing the password, this will change it in all
		places where the account is defined such as databases
		or text files.
		</p>
		<p>
		Note that you cannot change passwords that are used via
		LDAP or Certificates
		</p>
	</div>

	<div class='span-10' style='height: 35px; background-color: #eee; text-align: center; padding-top: 10px;'>
		<input id='faqDialogClose' type='button' value='Ok, thanks!'>
	</div>
</div>
