<div id='advanced' class='span-22 prepend-top append-bottom prepend-1 append-1 config advanced'>
	<div class='span-22'>
		I would like to make changes to the&nbsp;

		<select id='selectAdvanced'>
			<option value='adv-database-settings'>Database settings
			<option value='adv-fragile-devices'>Fragile devices
			<option value='adv-global-variable-settings'>Global variable settings
			<option value='adv-http-login-page'>HTTP login page
			<option value='adv-login-configurations'>Login configurations
			<option value='adv-nessus-scanners'>Nessus scanners
			<option value='adv-news-server-info-disclosure'>News Server (NNTP) information disclosure
			<option value='adv-ping-remote-host'>Remote host ping
			<option value='adv-port-scanner-settings'>Port scanner settings
			<option value='adv-smb-settings'>SMB settings
			<option value='adv-smtp-settings'>SMTP settings
			<option value='adv-snmp-settings'>SNMP settings
			<option value='adv-service-detection'>Service detection
			<option value='adv-web-app-test-settings'>Web application test settings
			<option value='adv-web-mirroring'>Web mirroring settings
		</select>

		<hr class='space'/>
		<hr class='quiet'/>

		<?php require 'form-advanced-database-settings.phtml'; ?>
		<?php require 'form-advanced-fragile-devices.phtml'; ?>
		<?php require 'form-advanced-global-variable-settings.phtml'; ?>
		<?php require 'form-advanced-http-login-page.phtml'; ?>
		<?php require 'form-advanced-login-configurations.phtml'; ?>
		<?php require 'form-advanced-nessus-scanners.phtml'; ?>
		<?php require 'form-advanced-news-server-info-disclosure.phtml'; ?>
		<?php require 'form-advanced-ping-remote-host.phtml'; ?>
		<?php require 'form-advanced-port-scanner-settings.phtml'; ?>
		<?php require 'form-advanced-smb-settings.phtml'; ?>
		<?php require 'form-advanced-smtp-settings.phtml'; ?>
		<?php require 'form-advanced-snmp-settings.phtml'; ?>
		<?php require 'form-advanced-service-detection.phtml'; ?>
		<?php require 'form-advanced-web-app-test-settings.phtml'; ?>
		<?php require 'form-advanced-web-mirroring.phtml'; ?>
	</div>
</div>
