<div id='credentials' class='span-22 prepend-top append-bottom prepend-1 append-1 config advanced'>
	<div class='span-22'>
		I would like to make changes to the&nbsp;

		<select id='selectCredentials'>
			<option value='cred-windows'>Windows credentials
			<option value='cred-ssh'>SSH settings
			<option value='cred-oracle'>Oracle settings
			<option value='cred-kerberos'>Kerberos configuration
			<option value='cred-cleartext'>Cleartext protocol settings
		</select>

		<hr class='space'/>
		<hr class='quiet'/>

		<?php require 'form-credentials-windows.phtml'; ?>
		<?php require 'form-credentials-ssh.phtml'; ?>
		<?php require 'form-credentials-oracle.phtml'; ?>
		<?php require 'form-credentials-kerberos.phtml'; ?>
		<?php require 'form-credentials-cleartext.phtml'; ?>
	</div>
</div>
