<div id='cred-kerberos' class='credential'>
	<div class='span-21'>
		<strong>Kerberos Key Distribution Center (KDC)</strong>
		<div>
			<?php if ($this->isNew): ?>
			<input type='text' name='plugin_preference[kerberosKdc]' value=''>
			<?php else: ?>
			<input type='text' name='plugin_preference[kerberosKdc]' value='<?php echo $this->policy->preferences->kerberosKdc; ?>'>
			<?php endif; ?>
		</div>

		<hr class='space'/>

		<strong>Kerberos KDC Port</strong>
		<div>
			<?php if ($this->isNew || $this->policy->preferences->kerberosKdcPort == null): ?>
			<input type='text' name='plugin_preference[kerberosKdcPort]' value='88'>
			<?php else: ?>
			<input type='text' name='plugin_preference[kerberosKdcPort]' value='<?php echo $this->policy->preferences->kerberosKdcPort; ?>'>
			<?php endif; ?>
		</div>

		<hr class='space'/>

		<strong>Kerberos KDC Transport</strong>
		<div>
			<select name='plugin_preference[kerberosKdcTransport]'>
				<?php if ($this->isNew): ?>
					<option value='udp' selected='selected'>udp
					<option value='tcp'>tcp
				<?php else: ?>
					<?php if ($this->policy->preferences->kerberosKdcTransport == 'tcp'): ?>
					<option value='udp'>udp
					<option value='tcp' selected='selected'>tcp
					<?php else: ?>
					<option value='udp' selected='selected'>udp
					<option value='tcp'>tcp
					<?php endif; ?>
				<?php endif; ?>
			</select>
		</div>

		<hr class='space'/>

		<strong>Kerberos Realm (SSH only)</strong>
		<div>
			<?php if ($this->isNew): ?>
			<input type='text' name='plugin_preference[kerberosRealm]' value=''>
			<?php else: ?>
			<input type='text' name='plugin_preference[kerberosRealm]' value='<?php echo $this->policy->preferences->kerberosRealm; ?>'>
			<?php endif; ?>
		</div>
	</div>
</div>
