<div id='cred-ssh' class='credential'>
	<div class='span-21'>
		<strong>SSH user name</strong>
		<div>
			<?php if ($this->isNew || $this->policy->preferences->sshUsername == null): ?>
			<input type='text' name='plugin_preference[sshUsername]' value='root'>
			<?php else: ?>
			<input type='text' name='plugin_preference[sshUsername]' value='<?php echo $this->policy->preferences->sshUsername; ?>'>
			<?php endif; ?>
		</div>

		<hr class='space'/>

		<strong>SSH password</strong>
		<div>
			<?php if ($this->isNew): ?>
			<input type='text' name='plugin_preference[sshPassword]' value=''>
			<?php else: ?>
			<input type='text' name='plugin_preference[sshPassword]' value='<?php echo $this->policy->preferences->sshPassword; ?>'>
			<?php endif; ?>
		</div>

		<hr class='space'/>

		<strong>Elevate privileges with</strong>
		<div>
			<select id='elevate-privs' name='plugin_preference[sshElevatePrivilegesWith]'>
			<?php if ($this->isNew): ?>
				<option value='Nothing' selected='selected'>Nothing
				<option value='sudo'>sudo
				<option value='su'>su
			<?php else: ?>
				<?php if ($this->policy->preferences->sshElevatePrivilegesWith == 'sudo'): ?>
					<option value='Nothing'>Nothing
					<option value='sudo' selected='selected'>sudo
					<option value='su'>su
				<?php elseif ($this->policy->preferences->sshElevatePrivilegesWith == 'su'): ?>
					<option value='Nothing'>Nothing
					<option value='sudo'>sudo
					<option value='su' selected='selected'>su
				<?php else: ?>
					<option value='Nothing' selected='selected'>Nothing
					<option value='sudo'>sudo
					<option value='su'>su
				<?php endif; ?>
			<?php endif; ?>
			</select>
			<div class='prepend-1 elevate-password'>
				<?php if ($this->isNew): ?>
				Password <input type='text' name='plugin_preference[sshSuPassword]' value=''>
				<?php else: ?>
				Password <input type='text' name='plugin_preference[sshSuPassword]' value='<?php echo $this->policy->preferences->sshSuPassword; ?>'>
				<?php endif; ?>
			</div>
		</div>

		<hr class='space'/>

		<strong>Preferred SSH port</strong>
		<div>
			<?php if ($this->isNew || $this->policy->preferences->sshPreferredPort == null): ?>
			<input type='text' name='plugin_preference[sshPreferredPort]' value='22'>
			<?php else: ?>
			<input type='text' name='plugin_preference[sshPreferredPort]' value='<?php echo $this->policy->preferences->sshPreferredPort; ?>'>
			<?php endif; ?>
		</div>
	</div>
</div>
