<div id='cred-oracle' class='credential'>
	<div class='span-21'>
		<strong>Oracle SID</strong>
		<div>
			<?php if ($this->isNew): ?>
			<input type='text' name='plugin_preference[oracleOracleSid]' value=''>
			<?php else: ?>
			<input type='text' name='plugin_preference[oracleOracleSid]' value='<?php echo $this->policy->preferences->oracleOracleSid; ?>'>
			<?php endif; ?>
		</div>

		<hr class='space'/>

		<strong>Miscellaneous</strong>
		<div>
			<?php if ($this->isNew): ?>
				<input type='checkbox' name='plugin_preference[oracleTestDefaultAccounts]'>Test default accounts<br>
			<?php else: ?>
				<?php if ($this->filter->filter($this->policy->preferences->oracleTestDefaultAccounts)): ?>
				<input type='checkbox' name='plugin_preference[oracleTestDefaultAccounts]' checked='checked'>Test default accounts<br>
				<?php else: ?>
				<input type='checkbox' name='plugin_preference[oracleTestDefaultAccounts]'>Test default accounts<br>
				<?php endif; ?>
			<?php endif; ?>
		</div>
	</div>
</div>
