<div id='cred-cleartext' class='credential'>
	<div class='span-21'>
		<strong>Username</strong>
		<div>
			<?php if ($this->isNew): ?>
			<input type='text' name='plugin_preference[cleartextUsername]' value=''>
			<?php else: ?>
			<input type='text' name='plugin_preference[cleartextUsername]' value='<?php echo $this->policy->preferences->cleartextUsername; ?>'>
			<?php endif; ?>
		</div>

		<hr class='space'/>

		<strong>Password (unsafe!)</strong>
		<div>
			<?php if ($this->isNew): ?>
			<input type='text' name='plugin_preference[cleartextPassword]' value=''>
			<?php else: ?>
			<input type='text' name='plugin_preference[cleartextPassword]' value='<?php echo $this->policy->preferences->cleartextPassword; ?>'>
			<?php endif; ?>
		</div>

		<hr class='space'/>

		<strong>Miscellaneous</strong>
		<div>
			<?php if ($this->isNew): ?>
				<input type='checkbox' name='plugin_preference[cleartextPatchChecksViaTelnet]'>Try to perform patch level checks over telnet<br>
				<input type='checkbox' name='plugin_preference[cleartextPatchChecksViaRsh]'>Try to perform patch level checks over rsh<br>
				<input type='checkbox' name='plugin_preference[cleartextPatchChecksViaRexec]'>Try to perform patch level checks over rexec

			<?php else: ?>
				<?php if ($this->filter->filter($this->policy->preferences->cleartextPatchChecksViaTelnet)): ?>
				<input type='checkbox' name='plugin_preference[cleartextPatchChecksViaTelnet]' checked='checked'>Try to perform patch level checks over telnet<br>
				<?php else: ?>
				<input type='checkbox' name='plugin_preference[cleartextPatchChecksViaTelnet]'>Try to perform patch level checks over telnet<br>
				<?php endif; ?>

				<?php if ($this->filter->filter($this->policy->preferences->cleartextPatchChecksViaRsh)): ?>
				<input type='checkbox' name='plugin_preference[cleartextPatchChecksViaRsh]' checked='checked'>Try to perform patch level checks over rsh<br>
				<?php else: ?>
				<input type='checkbox' name='plugin_preference[cleartextPatchChecksViaRsh]'>Try to perform patch level checks over rsh<br>
				<?php endif; ?>

				<?php if ($this->filter->filter($this->policy->preferences->cleartextPatchChecksViaRexec)): ?>
				<input type='checkbox' name='plugin_preference[cleartextPatchChecksViaRexec]' checked='checked'>Try to perform patch level checks over rexec
				<?php else: ?>
				<input type='checkbox' name='plugin_preference[cleartextPatchChecksViaRexec]'>Try to perform patch level checks over rexec
				<?php endif; ?>
			<?php endif; ?>
		</div>
	</div>
</div>
