<div id='cred-windows' class='credential first-credential'>
	<div class='span-22'>
		<div class='span-6 append-1'>
			<strong>SMB account</strong>
			<div>
				<?php if ($this->isNew): ?>
				<input type='text' name='plugin_preference[loginConfigSmbAccount]' value=''>
				<?php else: ?>
				<input type='text' name='plugin_preference[loginConfigSmbAccount]' value='<?php echo $this->policy->preferences->loginConfigSmbAccount; ?>'>
				<?php endif; ?>
			</div>
		</div>

		<div class='span-7 append-1'>
			<strong>SMB password</strong>
			<div>
				<?php if ($this->isNew): ?>
				<input type='text' name='plugin_preference[loginConfigSmbPassword]' value=''>
				<?php else: ?>
				<input type='text' name='plugin_preference[loginConfigSmbPassword]' value='<?php echo $this->policy->preferences->loginConfigSmbPassword; ?>'>
				<?php endif; ?>
			</div>
		</div>

		<div class='span-7 last'>
			<strong>SMB domain (optional)</strong>
			<div>
				<?php if ($this->isNew): ?>
				<input type='text' name='plugin_preference[loginConfigSmbDomain]' value=''>
				<?php else: ?>
				<input type='text' name='plugin_preference[loginConfigSmbDomain]' value='<?php echo $this->policy->preferences->loginConfigSmbDomain; ?>'>
				<?php endif; ?>
			</div>
		</div>

		<hr class='space'/>

		<strong>SMB password type</strong>
		<div>
			<select name='plugin_preference[loginConfigSmbPasswordType]'>
			<?php if ($this->isNew): ?>
				<option value='Password' selected='selected'>Password
				<option value='LM Hash'>LM Hash
				<option value='NTLM Hash'>NTLM Hash
			<?php else: ?>
				<?php if ($this->policy->preferences->loginConfigSmbPasswordType == 'LM Hash'): ?>
					<option value='Password'>Password
					<option value='LM Hash' selected='selected'>LM Hash
					<option value='NTLM Hash'>NTLM Hash
				<?php elseif ($this->policy->preferences->loginConfigSmbPasswordType == 'NTLM Hash'): ?>
					<option value='Password'>Password
					<option value='LM Hash'>LM Hash
					<option value='NTLM Hash' selected='selected'>NTLM Hash
				<?php else: ?>
					<option value='Password' selected='selected'>Password
					<option value='LM Hash'>LM Hash
					<option value='NTLM Hash'>NTLM Hash
				<?php endif; ?>
			<?php endif; ?>
			</select>
		</div>

		<hr class='space'/>

		<div class='add-windows-credential hypertext'>add additional Windows credentials</div>

		<div>
			<div class='smb-credential prepend-1'>
				<div class='span-21 prepend-top append-bottom' style='border-bottom: 1px solid #eee;'>
					<div class='span-10'>
						<strong>Additional SMB account 1</strong>
					</div>
					<div class='span-11 last remove-credential'>
						<span class='hypertext remove-windows-credential'><img src='<?php echo $this->baseUrl(); ?>/usr/images/trash.gif'></span>
					</div>
				</div>

				<div class='span-21 append-bottom'>
					<div class='span-6 append-1'>
						<span class='input-header'>Account</span><span class='required'>*</span>
						<div>
							<?php if ($this->isNew): ?>
							<input class='smb-account plugin' type='text' name='plugin_preference[loginConfigSmbAccount1]' value=''>
							<?php else: ?>
							<input class='smb-account plugin' type='text' name='plugin_preference[loginConfigSmbAccount1]' value='<?php echo $this->policy->preferences->loginConfigSmbAccount1; ?>'>
							<?php endif; ?>
						</div>
					</div>

					<div class='span-6 append-1'>
						<span class='input-header'>Password</span><span class='required'>*</span>
						<div>
							<?php if ($this->isNew): ?>
							<input type='text' name='plugin_preference[loginConfigSmbPassword1]' value=''>
							<?php else: ?>
							<input type='text' name='plugin_preference[loginConfigSmbPassword1]' value='<?php echo $this->policy->preferences->loginConfigSmbPassword1; ?>'>
							<?php endif; ?>
						</div>
					</div>

					<div class='span-7 last'>
						<span class='input-header'>Domain</span>
						<div>
							<?php if ($this->isNew): ?>
							<input type='text' name='plugin_preference[loginConfigSmbDomain1]' value=''>
							<?php else: ?>
							<input type='text' name='plugin_preference[loginConfigSmbDomain1]' value='<?php echo $this->policy->preferences->loginConfigSmbDomain1; ?>'>
							<?php endif; ?>
						</div>
					</div>
				</div>
			</div>

			<div class='smb-credential prepend-1'>
				<div class='span-21 append-bottom' style='border-bottom: 1px solid #eee;'>
					<div class='span-10'>
						<strong>Additional SMB account 2</strong>
					</div>
					<div class='span-11 last remove-credential'>
						<span class='hypertext remove-windows-credential'><img src='<?php echo $this->baseUrl(); ?>/usr/images/trash.gif'></span>
					</div>
				</div>

				<div class='span-21 append-bottom'>
					<div class='span-6 append-1'>
						<span class='input-header'>Account</span><span class='required'>*</span>
						<div>
							<?php if ($this->isNew): ?>
							<input class='smb-account plugin' type='text' name='plugin_preference[loginConfigSmbAccount2]' value=''>
							<?php else: ?>
							<input class='smb-account plugin' type='text' name='plugin_preference[loginConfigSmbAccount2]' value='<?php echo $this->policy->preferences->loginConfigSmbAccount2; ?>'>
							<?php endif; ?>
						</div>
					</div>

					<div class='span-6 append-1'>
						<span class='input-header'>Password</span><span class='required'>*</span>
						<div>
							<?php if ($this->isNew): ?>
							<input type='text' name='plugin_preference[loginConfigSmbPassword2]' value=''>
							<?php else: ?>
							<input type='text' name='plugin_preference[loginConfigSmbPassword2]' value='<?php echo $this->policy->preferences->loginConfigSmbPassword2; ?>'>
							<?php endif; ?>
						</div>
					</div>

					<div class='span-7 last'>
						<span class='input-header'>Domain</span>
						<div>
							<?php if ($this->isNew): ?>
							<input type='text' name='plugin_preference[loginConfigSmbDomain2]' value=''>
							<?php else: ?>
							<input type='text' name='plugin_preference[loginConfigSmbDomain2]' value='<?php echo $this->policy->preferences->loginConfigSmbDomain2; ?>'>
							<?php endif; ?>
						</div>
					</div>
				</div>
			</div>

			<div class='smb-credential prepend-1'>
				<div class='span-21 append-bottom' style='border-bottom: 1px solid #eee;'>
					<div class='span-10'>
						<strong>Additional SMB account 3</strong>
					</div>
					<div class='span-11 last remove-credential'>
						<span class='hypertext remove-windows-credential'><img src='<?php echo $this->baseUrl(); ?>/usr/images/trash.gif'></span>
					</div>
				</div>

				<div class='span-21'>
					<div class='span-6 append-1'>
						<span class='input-header'>Account</span><span class='required'>*</span>
						<div>
							<?php if ($this->isNew): ?>
							<input class='smb-account plugin' type='text' name='plugin_preference[loginConfigSmbAccount3]' value=''>
							<?php else: ?>
							<input class='smb-account plugin' type='text' name='plugin_preference[loginConfigSmbAccount3]' value='<?php echo $this->policy->preferences->loginConfigSmbAccount3; ?>'>
							<?php endif; ?>
						</div>
					</div>

					<div class='span-6 append-1'>
						<span class='input-header'>Password</span><span class='required'>*</span>
						<div>
							<?php if ($this->isNew): ?>
							<input type='text' name='plugin_preference[loginConfigSmbPassword3]' value=''>
							<?php else: ?>
							<input type='text' name='plugin_preference[loginConfigSmbPassword3]' value='<?php echo $this->policy->preferences->loginConfigSmbPassword3; ?>'>
							<?php endif; ?>
						</div>
					</div>

					<div class='span-7 last'>
						<span class='input-header'>Domain</span>
						<div>
							<?php if ($this->isNew): ?>
							<input type='text' name='plugin_preference[loginConfigSmbDomain3]' value=''>
							<?php else: ?>
							<input type='text' name='plugin_preference[loginConfigSmbDomain3]' value='<?php echo $this->policy->preferences->loginConfigSmbDomain3; ?>'>
							<?php endif; ?>
						</div>
					</div>
				</div>
			</div>
		</div>

		<hr class='space'/>

		<strong>Miscellaneous</strong>
		<div class='prepend-1'>
			<?php if ($this->isNew): ?>
				<input type='checkbox' name='plugin_preference[loginConfigNeverSendSmbCredsClear]' checked='checked'>Never send SMB credentials in clear text<br>
				<input type='checkbox' name='plugin_preference[loginConfigOnlyNtlmv2]'>Only use NTLMv2
			<?php else: ?>
				<?php if ($this->filter->filter($this->policy->preferences->loginConfigNeverSendSmbCredsClear)): ?>
				<input type='checkbox' name='plugin_preference[loginConfigNeverSendSmbCredsClear]' checked='checked'>Never send SMB credentials in clear text<br>
				<?php else: ?>
				<input type='checkbox' name='plugin_preference[loginConfigNeverSendSmbCredsClear]'>Never send SMB credentials in clear text<br>
				<?php endif; ?>

				<?php if ($this->filter->filter($this->policy->preferences->loginConfigOnlyNtlmv2)): ?>
				<input type='checkbox' name='plugin_preference[loginConfigOnlyNtlmv2]' checked='checked'>Only use NTLMv2
				<?php else: ?>
				<input type='checkbox' name='plugin_preference[loginConfigOnlyNtlmv2]'>Only use NTLMv2
				<?php endif; ?>
			<?php endif; ?>
		</div>
	</div>
</div>
