<div id='title' class='span-24' style='background-color: #ededed; line-height: 35px; height: 35px;'>
	<div class='span-5'>
<?php if ($this->isNew === true): ?>
		<div style='padding-left: 10px; font-size: 1.4em;'>
			<a href='<?php echo $this->baseUrl(); ?>/policy' class='hypertext'>Policies</a> &raquo;
			<span>Create policy</span>
			<img class='progress' src='<?php echo $this->baseUrl(); ?>/usr/images/spinner.gif'>
		</div>
<?php else: ?>
		<div style='padding-left: 10px; font-size: 1.6em;'>
			<a href='<?php echo $this->baseUrl(); ?>/policy' class='hypertext'>Policies</a> &raquo;
			Edit
			<img class='progress' src='<?php echo $this->baseUrl(); ?>/usr/images/spinner.gif'>
		</div>
<?php endif; ?>
	</div>

	<div id='menu' class='span-19 last' style='text-align: right;'>
		<div class='pluginLinks'>
			<ul>
				<li><a href="#general" class='darkHypertext'>General</a>
				<li><a href="#options" class='darkHypertext'>Options</a>
				<li><a href="#credentials" class='darkHypertext'>Credentials</a>
				<li><a href="#plugins" class='darkHypertext'>Plugins</a>
				<li><a href="#network" class='darkHypertext'>Network</a>
				<li><a href="#advanced" class='darkHypertext'>Advanced</a>
			</ul>
		</div>
	</div>
</div>
