<?php require _MODPATH.'/default/views/scripts/header/index.phtml'; ?>

<div class='span-22 last'>
	<span style='font-size: 1.5em;'>Plugin tools</span>
</div>
<hr class='space'/>
<div class='span-15 colborder'>
	<ul>
		<li><a class='hypertext' href='<?php echo $this->baseUrl(); ?>/admin/tools/archive-index'>Archive maker</a>
		<li><a class='hypertext' href='<?php echo $this->baseUrl(); ?>/admin/tools/plugin-search-index'>Plugin search</a>
	</ul>
</div>
<div class='span-6 last' style='text-align: justify;'>
	<p>
	nessquik includes a couple of tools that can be used to make
	administration of plugins or usage of those plugins easier
	</p>
</div>

<?php require _MODPATH.'/default/views/scripts/footer/index.phtml'; ?>
