<?php require _MODPATH.'/default/views/scripts/header/index.phtml'; ?>

<div class='span-22 last'>
	<div class='span-16' style='font-size: 1.5em;'>Create new role</div>
</div>
<hr class='space'/>
<div class='span-15 colborder'>
	<form method='post' action='<?php echo $this->baseUrl(); ?>/admin/roles/save'>
		<strong>Role name</strong>
		<div>
			<input type='text' style='width: 100%;' name='role-name'>
		</div>

		<hr class='space'/>

		<strong>Description</strong>
		<div>
			<textarea style='width: 98%; height: 120px;' name='role-description'></textarea>
		</div>

		<hr class='space'/>

		<div class='span-15 last clearfix' style='text-align: center;'>
			<input type='submit' value='Create role'>
			<a class='hypertext' style='padding-left: 20px;' href='<?php echo $this->baseUrl(); ?>/admin/roles'>I've decided to not create a role</a>
		</div>
	</form>
</div>
<div class='span-6 last' style='text-align: justify;'>
	<p>
	Roles allow you to fine tune the security and administration of nessquik.
	</p>
	<p>
	A role defines a group of users that have certain privileges as defined
	in user permissions. Examples of roles include: anonymous user, authenticated user,
	administrator and so on. In this area you will define the role names of
	the various roles.
	</p>
</div>

<?php require _MODPATH.'/default/views/scripts/footer/index.phtml'; ?>
