<div id='faqDialog'>
	<div class='span-10' style='border-bottom: 1px solid #eee; background-color: #eee; height: 35px; min-height: 35px;'>
		<div style='padding: 10px;'>
			<div style='color: #303233; font-weight: bold;'>
				Help
			</div>
		</div>
	</div>

	<div class='prepend-1 append-1 prepend-top append-bottom span-8'>
		<p>
		nessquik requires that you have an account in the system before you
		can make use of any portion of the system.
		</p>
		<p>
		Accounts allow for separation of policies and customization of the
		environment to the particular user. They also allow for data sharing
		between different users.
		</p>
		<p>
		Accounts are used by more than just people though. Portions of nessquik
		run in an automated fashion. Even these parts have accounts in the
		system so that roles and other forms of access control can be applied
		to them.
		</p>
	</div>

	<div class='span-10' style='height: 35px; background-color: #eee; text-align: center; padding-top: 10px;'>
		<input id='faqDialogClose' type='button' value='Ok, thanks!'>
	</div>
</div>
