<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/jquery/plugins/jquery.tablesorter.min.js' type='text/javascript'></script>
<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/jquery/plugins/jquery.ba-throttle-debounce.min.js' type='text/javascript'></script>
<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/audit/status/index.js' type='text/javascript'></script>
