<?php require _MODPATH.'/default/views/scripts/header/index.phtml'; ?>
<?php require _MODPATH.'/charts/views/scripts/header/index.phtml'; ?>

<div class='span-22'>
	<form id='form-edit'>
		<input type='hidden' name='base-url' value='<?php echo $this->baseUrl(); ?>'>
	</form>

	<div id='urlActivityLastDayBar' class='span-22 append-bottom'>
		<div class='span-22'>
			<strong>About this chart</strong>
		</div>
		<div class='small quiet append-bottom span-22'>
			This chart shows URL creation activity in savory over the last 24 hours
		</div>
		<div class='progress span-22'>
			<img src='<?php echo $this->baseUrl(); ?>/usr/images/spinner.gif'>
		</div>
		<div class='message error span-22'>
			<div class='content'></div>
		</div>
		<div id='urlActivityLastDayBarChart' class='span-22' style='height: 300px; text-align: center;'></div>
	</div>
</div>

<?php require _MODPATH.'/default/views/scripts/footer/index.phtml'; ?>
