<div id='title' class='span-24' style='background-color: #ededed; line-height: 35px; height: 35px;'>
	<div class='span-6'>
		<div style='padding-left: 10px; font-size: 1.6em;'>
			Metrx
			<img class='progress' src='<?php echo $this->baseUrl(); ?>/usr/images/spinner.gif'>
		</div>
	</div>

	<div id='menu' class='span-18 last' style='text-align: right;'>
		<div class='pluginLinks'>
			<ul>
				<li><a class='darkHypertext' href='#charts'>Charts</a></li>
				<li><a class='darkHypertext' href='#reports'>Reports</a></li>
				<li><a class='darkHypertext' href='#tables'>Tables</a></li>
			</ul>
		</div>
	</div>
</div>
